### ISSUE TITLE
SSWoC Frame Filter

### ISSUE THREAD

**Issue by theDeviser** [SnowScriptWinterOfCode/FilterFiesta#4]
I'm looking forward to create an official filter for the SSWoC program using the spark AR studio, please assign this issue to me

**Comment by theDeviser** [comment]
I'm already done with the designing phase just need a quick review of the following samples
Which one is preferred by the GDSC IGDTUW's Team
1:
![image](https://github.com/SnowScriptWinterOfCode/FilterFiesta/assets/92399093/5ca79a29-308d-4d62-b0fb-e763cfa64d77)
2:
![image](https://github.com/SnowScriptWinterOfCode/FilterFiesta/assets/92399093/92874820-df4b-45f9-9ac8-ef09e80079c1)

**Comment by rhymasharma** [comment]
I'd personally prefer 1 over 2. It looks more concise :)
